TEXT_BOX_WIDTH_PERCENTAGE = 75
TEXT_BOX_HEIGHT_PERCENTAGE_1 = 25
TEXT_BOX_HEIGHT_PERCENTAGE_2 = 20
TEXT_BOX_HEIGHT_PERCENTAGE_3 = 10

BUTTON_HEIGHT_PERCENTAGE = 5
PROGRESS_BAR_HEIGHT_PERCENTAGE = 3

PROGRESS_RING_HEIGHT_PERCENTAGE = 10
PROGRESS_RING_WIDTH_PERCENTAGE = 10

VERTICAL_LINE_WIDTH_PERCENTAGE = 1

FONT_SIZE_1 = 25
FONT_SIZE_2 = 20
FONT_SIZE_3 = 15

SPACED_REPETITION_CATEGORIES = ["Unseen", "Learning", "Reviewing", "Mastered"]
